#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

#define LV_COLOR_DEPTH 16

// 模拟器展示性能监控
// #define LV_USE_SYSMON        1
// #define LV_USE_PERF_MONITOR  1
// #define LV_USE_PERF_MONITOR_POS LV_ALIGN_BOTTOM_RIGHT

#define LV_USE_STDLIB_MALLOC  LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING  LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB

#define LV_USE_OS LV_OS_NONE

#define LV_USE_THEME_DEFAULT 1

#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_28 1

#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN

#define LV_USE_BMP 1

#define LV_USE_SDL 0

#endif
