idf_component_register(
    SRCS
        "nofrendo.c"
        "nes/apu.c"
        "nes/cpu.c"
        "nes/dis.c"
        "nes/input.c"
        "nes/mem.c"
        "nes/mmc.c"
        "nes/nes.c"
        "nes/ppu.c"
        "nes/rom.c"
        "nes/state.c"
        "mappers/map000.c"
        "mappers/map001.c"
        "mappers/map002.c"
        "mappers/map003.c"
        "mappers/map004.c"
        "mappers/map005.c"
        "mappers/map007.c"
        "mappers/map009.c"
        "mappers/map010.c"
        "mappers/map011.c"
        "mappers/map015.c"
        "mappers/map016.c"
        "mappers/map018.c"
        "mappers/map019.c"
        "mappers/map020.c"
        "mappers/map021.c"
        "mappers/map022.c"
        "mappers/map023.c"
        "mappers/map024.c"
        "mappers/map030.c"
        "mappers/map031.c"
        "mappers/map032.c"
        "mappers/map033.c"
        "mappers/map034.c"
        "mappers/map040.c"
        "mappers/map041.c"
        "mappers/map042.c"
        "mappers/map046.c"
        "mappers/map050.c"
        "mappers/map064.c"
        "mappers/map065.c"
        "mappers/map066.c"
        "mappers/map070.c"
        "mappers/map071.c"
        "mappers/map073.c"
        "mappers/map074.c"
        "mappers/map075.c"
        "mappers/map076.c"
        "mappers/map078.c"
        "mappers/map079.c"
        "mappers/map085.c"
        "mappers/map087.c"
        "mappers/map093.c"
        "mappers/map094.c"
        "mappers/map119.c"
        "mappers/map160.c"
        "mappers/map162.c"
        "mappers/map176.c"
        "mappers/map185.c"
        "mappers/map191.c"
        "mappers/map192.c"
        "mappers/map193.c"
        "mappers/map194.c"
        "mappers/map195.c"
        "mappers/map206.c"
        "mappers/map228.c"
        "mappers/map229.c"
        "mappers/map231.c"
    INCLUDE_DIRS "." "nes" "mappers"
    REQUIRES spi_flash)

target_compile_options(${COMPONENT_LIB} PRIVATE
    -O3
    -Wno-char-subscripts
    -Wno-array-bounds
    -Wno-error=format
    -Wno-format
    -mfix-esp32-psram-cache-issue
    -mfix-esp32-psram-cache-strategy=memw)
